### ISSUE TITLE
Error in hash to plaintext for ntlm9

### ISSUE THREAD

**Issue by Sc00bz** [jtesta/rainbowcrackalack#1]
In `hash_to_index_ntlm9()` it is modulo 6634204312890625 which is 95^8 not 95^9:
https://github.com/jtesta/rainbowcrackalack/blob/cbf745288d75b55f0a5c3ec57b3a818f77e94b1b/CL/ntlm9_functions.cl#L157

Also `index_to_plaintext_ntlm9()` assumes it's a full 64 bit int:
https://github.com/jtesta/rainbowcrackalack/blob/cbf745288d75b55f0a5c3ec57b3a818f77e94b1b/CL/ntlm9_functions.cl#L14-L15

Leaving `index_to_plaintext_ntlm9()` unchanged will cause a high bias in the passwords. Since the first 66 characters in the character set have a probability of 1.171875% (3/256) each vs the last 29 characters have 0.78125% (2/256) each. This will cause more collisions and lower the success rate.

**Comment by llamasoft** [comment]
I agree with Sc00bz here.  Honestly, the division method is slower but a much better method.  The primary reason it's 2.4x slower in OpenCL than the 7-bit trick is because it has a lot of conditional and data dependent branching which kills performance.  That said, it _can_ be optimized to take a constant amount of time.  It'll still have _some_ modulo bias, but it will be less than the 7-bit method.

I think it may also be worth looking into using the whole hash as the input to the reduction function instead of condensing it to a 64-bit index first.  Passing the largest possible value to the reduction function reduces the number of modulo operations which reduces the amount of modulo bias (i.e.  `2^128 % keyspace` is going to have less bias than `2^64 % keyspace`).

**Comment by jtesta** [comment]
> In `hash_to_index_ntlm9()` it is modulo 6634204312890625 which is 95^8 not 95^9:

Excellent find!

This function is not currently active, however.  I disabled it in _crackalack_gen.c:227_.  I was last working on that part months ago, so I don't remember why, but I'd guess its because the bug you found prevented it from working and I couldn't figure it out at the time.

> Leaving index_to_plaintext_ntlm9() unchanged will cause a high bias in the passwords.

Another excellent find.  I've opened a separate issue for this (#2).

**Comment by Sc00bz** [comment]
@llamasoft doing 128 bit math is going to be very slow. I could see doing something like 80 bits. That decrease the chance of a bias to 1 in 3.9 million vs 1 in 109. Also bias is 1,918,171/1,918,170 vs 30/29.

**Comment by llamasoft** [comment]
@Sc00bz Normally, yes, but we can bend the rules here.  We don't need to do "proper" 128 bit math where long division needs to preserve endianness.  The input hash is a pseudo-random value so it's not an issue if we mix up the byte ordering by treating it as N M-bit values (e.g. two 64-bit values, four 32-bit values, ...).

Given that modulo is distributive, we can calculate `hash % keyspace` in a constant number of operations based on how small we chunk the hash.  This works because `hash` can be rewritten as the sum of its shifted parts.  
For example, when broken into four 32-bit values, it can be rewritten as `(a * 2^96) + (b * 2^64) + (c * 2^32) + d`. This value can be computed iteratively in _constant_ time:
- `temp = a`
- `temp = ((temp << 32) | b) % keyspace`
- `temp = ((temp << 32) | c) % keyspace`
- `temp = ((temp << 32) | d) % keyspace`

Yes, we may end up throwing away bits if the shift operation overflows, but even in the absolute worst case we only throw away 64 bits (which is how many the code is currently discarding).  We can even decrease the likelihood of discarded bits by splitting `hash` into smaller chunks in exchange for a few extra reduction iterations.

The reason I care so much is that any bias in the reduction function _will_ lead to chains with overlapping coverage.  We can either waste processing power and space generating low-value chains from a biased reduction function or we can spend a few extra cycles reducing bias and generate chains with less overlapping coverage.

**Comment by Sc00bz** [comment]
> * temp = a
> * temp = ((temp << 32) | b) % keyspace
> * temp = ((temp << 32) | c) % keyspace
> * temp = ((temp << 32) | d) % keyspace

If `temp` is a 64 bit int and `keyspace` is 95\*\*9 (2\*\*59.13) then you need to shift in 4 bits at a time. Otherwise this will increase bias because the lowest 32 bits after a modulo are less likely to be >3,732,696,636 (`((2**64 - 1) % (95**9)) % (2**32)`). It's a very small bias but this will be worst than just using 64 bit.

"Free Rainbow Tables" (FRT) generated tables with key spaces around 2\*\*53 and the bias in that didn't negatively effect it. So adding just a few bit like 16 bit is more than enough.
