### ISSUE TITLE
LM Support? 

### ISSUE THREAD

**Issue by infosecconsultant** [jtesta/rainbowcrackalack#29]
Any chance of LM/NetNTLMv1 rainbow table creation in future? 
Would be a huge help if possible.

**Comment by jtesta** [comment]
I actually generated LM tables myself for fun.  I never made them
public because they aren't that useful; you're better off doing a
brute-force search for LM.

As for other tables, I don't currently have plans to generate more
myself.  If someone else in the community wanted to organize another
project, I'd be happy to support it, though.  But be aware that this
takes MASSIVE amounts of time and effort to do!

**Comment by infosecconsultant** [comment]
Sorry. I wasn't specific there. I meant NET(NT)LM hashes. Using the known challenge 1122334455667788.
Straight LM cracks in a very short period of time these days with a GPU. 

I'm not sure how much processing power would be required to generate them but I could organise a non trivial number of people to get involved with generating them. 

If you are happy to adapt the code to produce NET(NT)LM hashes, I'd be happy to try organise people to provide some computing resources :)

**Comment by jtesta** [comment]
Unfortunately, I don't have much time to put towards development of new
code these days.  But if someone submitted a PR for NetNTLM / NetLM,
I'd be happy to merge it!

I'd also be happy to advertise the new table generation project on the
website and Github page in order to get even more volunteers.  But
sadly, that's the extent of what I'm able to do with my limited time...

**Comment by jtesta** [comment]
I'm closing this issue, but if you'd like to start the NetNTLM / NetLM project, please let me know!
