### ISSUE TITLE
Why can't my GPU be fully used all the time

### ISSUE THREAD

**Issue by Ajatars** [jtesta/rainbowcrackalack#32]
Why can't the GPU be fully utilized when exploding the rainbow meter?
./crackalack_lookup  /tmp/rainbowcrackalack/9_rt c8d9050093b615aa95b73cbd5ae63772 
![image](https://user-images.githubusercontent.com/51531502/133206818-5d6d67a9-1efb-46b4-be7b-8af199cb1d9f.png)

But we can make full use of GPU when generating rainbow table
./crackalack_gen ntlm ascii-32-95 9 9 0 803000 67108864 0 
![image](https://user-images.githubusercontent.com/51531502/133207327-8b27b326-bec8-47a8-bd64-06f43d7de5eb.png)

**Comment by jtesta** [comment]
Generating tables is very GPU-intensive by nature.  Lookups, on the
other hand, involve doing pre-computation (GPU-dominant), binary
searching within the tables (CPU-dominant), and finally false alarm
checks (GPU-dominant).

So when you're doing lookups, if your GPUs aren't being used, check
your CPU & disk usage.  You should see your CPU being mostly utilized
at that point.

-- 
Joseph S. Testa II
Founder & Principal Security Consultant
Positron Security

**Comment by Ajatars** [comment]
So doing lookups，is it normal that GPU utilization cannot be 100% all the time?

And the CPU in the whole process is no more than 51%
![image](https://user-images.githubusercontent.com/51531502/133561153-b701a1af-7305-4218-91b7-e147b34fc59c.png)

**Comment by jtesta** [comment]
> So doing lookups，is it normal that GPU utilization cannot be 100% all
the time?

Yes, that can be normal.  In your case, it seems like you're doing a
single hash lookup.  The precomputation phase would have taken 100% of
GPU power for a short period of time (note that the precomputation
results are cached in rcracki.precalc* files, so no precomputation is
done on subsequent lookups on the same hash).  The binary searching
step is done on the CPU.  The false alarm checks are done on the GPU,
but since you're only doing one hash lookup, there are very few checks
to do.  Hence, the GPU doesn't have much work to do in this phase.  If
you did a lookup on 100+ hashes, then the false alarm checks would
result in much higher GPU load.


> And the CPU in the whole process is no more than 51%

Since you're only doing one hash lookup, the CPU may not reach 100%.
 If you do many hash lookups at the same time, then you may see closer
to 100%.

Also, note that binary searching involves many memory read operations.
 So the speed of your memory controller may become a bottleneck before
the CPU reaches 100%.

-- 
Joseph S. Testa II
Founder & Principal Security Consultant
Positron Security

**Comment by jtesta** [comment]
I suppose I'll close this issue now.  But if you have any more questions, please let me know!
